### ISSUE TITLE
Code Style: Action should be shortest as possible, FormType should be a separated class

### ISSUE THREAD

**Issue by ViktorParakhonia** [mihail-p/testPrRedmine#6]
https://github.com/mihail-p/testPrRedmine/blob/0522e5abe602d3a231b3bdd35d487160daf9246f/src/AppBundle/Controller/TrackTimeController.php#L47

**Comment by mihail-p** [comment]
Corrected!
But do you know how to add "disabled" option to EntityType in editAction - CommentsController?

**Comment by ViktorParakhonia** [comment]
You can look to id of comment, on edit is present, on create is null, check it like: “disabled” => $builder->getData()->getId()

**Comment by ViktorParakhonia** [comment]
You don’t have to fix an issues, actually... that will not have effect on assessment
